repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: "go fmt"
        entry: go fmt ./...
        language: system
        files: '\.go$'
        pass_filenames: false
      - id: go-vet
        name: "go vet"
        entry: go vet ./...
        language: system
        files: '\.go$'
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-vcs-permalinks
      - id: check-shebang-scripts-are-executable
      - id: trailing-whitespace
      - id: check-symlinks
      - id: destroyed-symlinks
